# Site settings
title: Ricky Yim
description: Ricky Yim
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ricky Yim
twitter_username: codingricky
github_username: codingricky
linkedin_username: rickyyim
blog: https://www.codingricky.com
user_description: Technologist who runs, parents and watches too much basketball.

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

url: "http://rickyy.im" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap